# Generated by Django 5.0.2 on 2024-02-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackApp', '0002_teacher_number_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='User',
        ),
    ]
